# https://raw.githubusercontent.com/hbstack/site/main/config/_default/menus.en.yml

main:
  - name: Universal
    identifier: universal
    weight: 1
    params:
      icon:
        vendor: bs
        name: book

  - name: Canadian-Specific
    identifier: canadian
    weight: 2
    params:
      icon:
        vendor: bs
        name: book

  - name: Exams
    identifier: exams
    weight: 3
    params:
      icon:
        vendor: bs
        name: book

  - name: Specialty
    identifier: specialty
    weight: 4
    params:
      icon:
        vendor: bs
        name: book

