# https://raw.githubusercontent.com/hbstack/site/main/config/_default/menus.en.yml

main:
  - name: Fundamental Accounting Principles
    identifier: fundamental
    weight: 1
    params:
      icon:
        vendor: bs
        name: book

  - name: Intermediate Accounting Concepts
    identifier: intermediate
    weight: 2
    params:
      icon:
        vendor: bs
        name: book

  - name: Canadian-Specific Accounting Practices
    identifier: canadian
    weight: 4
    params:
      icon:
        vendor: bs
        name: book

  - name: Specialized Accounting Exam Preparation
    identifier: exams
    weight: 5
    params:
      icon:
        vendor: bs
        name: book

  - name: Accounting Ethics and Professionalism
    identifier: ethics
    weight: 6
    params:
      icon:
        vendor: bs
        name: book

